import type { Metadata } from "next";
// import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";
// import "@fontsource/lato/300.css";
// import "@fontsource/lato/400.css";
import { Lato } from "next/font/google";

const lato = Lato({
  weight: ["300", "400"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lato.className}>
      <body>
        <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
